[[ics]]
name = "Somador3bit"
pins = 24
vcc = 5
vectors = [
  "00000XXXXXXGXLLLXXXXXXXV",
  "00001XXXXXXGXLLHXXXXXXXV",
  "00010XXXXXXGXLHLXXXXXXXV",
  "00011XXXXXXGXLHHXXXXXXXV",
  "00100XXXXXXGXLLHXXXXXXXV",
  "00101XXXXXXGXLHLXXXXXXXV",
  "00110XXXXXXGXLHHXXXXXXXV",
  "00111XXXXXXGXHLLXXXXXXXV",
  "01000XXXXXXGXLHLXXXXXXXV",
  "01001XXXXXXGXLHHXXXXXXXV",
  "01010XXXXXXGXHLLXXXXXXXV",
  "01011XXXXXXGXHLHXXXXXXXV",
  "01100XXXXXXGXLHHXXXXXXXV",
  "01101XXXXXXGXHLLXXXXXXXV",
  "01110XXXXXXGXHLHXXXXXXXV",
  "01111XXXXXXGXHHLXXXXXXXV",
  "10000XXXXXXGXHLLXXXXXXXV",
  "10001XXXXXXGXHLHXXXXXXXV",
  "10010XXXXXXGXHHLXXXXXXXV",
  "10011XXXXXXGXHHHXXXXXXXV",
  "10100XXXXXXGXHLHXXXXXXXV",
  "10101XXXXXXGXHHLXXXXXXXV",
  "10110XXXXXXGXHHHXXXXXXXV",
  "10111XXXXXXGXLLLXXXXXXXV",
  "11000XXXXXXGXHHLXXXXXXXV",
  "11001XXXXXXGXHHHXXXXXXXV",
  "11010XXXXXXGXLLLXXXXXXXV",
  "11011XXXXXXGXLLHXXXXXXXV",
  "11100XXXXXXGXHHHXXXXXXXV",
  "11101XXXXXXGXLLLXXXXXXXV",
  "11110XXXXXXGXLLHXXXXXXXV",
  "11111XXXXXXGXLHLXXXXXXXV",
]
