[[ics]]
name = "Somador3bit"
pins = 24
vcc = 5
vectors = [
  "000000XXXXXGXLXLLXLXXXXV",
  "000001XXXXXGXLXLHXLXXXXV",
  "000010XXXXXGXLXHLXLXXXXV",
  "000011XXXXXGXLXHHXLXXXXV",
  "000100XXXXXGXLXLLXHXXXXV",
  "000101XXXXXGXLXLHXHXXXXV",
  "000110XXXXXGXLXHLXHXXXXV",
  "000111XXXXXGXLXHHXHXXXXV",
  "001000XXXXXGXLXLHXLXXXXV",
  "001001XXXXXGXLXHLXLXXXXV",
  "001010XXXXXGXLXHHXLXXXXV",
  "001011XXXXXGXLXLLXHXXXXV",
  "001100XXXXXGXLXLHXHXXXXV",
  "001101XXXXXGXLXHLXHXXXXV",
  "001110XXXXXGXLXHHXHXXXXV",
  "001111XXXXXGXHXLLXLXXXXV",
  "010000XXXXXGXLXHLXLXXXXV",
  "010001XXXXXGXLXHHXLXXXXV",
  "010010XXXXXGXLXLLXHXXXXV",
  "010011XXXXXGXLXLHXHXXXXV",
  "010100XXXXXGXLXHLXHXXXXV",
  "010101XXXXXGXLXHHXHXXXXV",
  "010110XXXXXGXHXLLXLXXXXV",
  "010111XXXXXGXHXLHXLXXXXV",
  "011000XXXXXGXLXHHXLXXXXV",
  "011001XXXXXGXLXLLXHXXXXV",
  "011010XXXXXGXLXLHXHXXXXV",
  "011011XXXXXGXLXHLXHXXXXV",
  "011100XXXXXGXLXHHXHXXXXV",
  "011101XXXXXGXHXLLXLXXXXV",
  "011110XXXXXGXHXLHXLXXXXV",
  "011111XXXXXGXHXHLXLXXXXV",
  "100000XXXXXGXLXLLXHXXXXV",
  "100001XXXXXGXLXLHXHXXXXV",
  "100010XXXXXGXLXHLXHXXXXV",
  "100011XXXXXGXLXHHXHXXXXV",
  "100100XXXXXGXHXLLXLXXXXV",
  "100101XXXXXGXHXLHXLXXXXV",
  "100110XXXXXGXHXHLXLXXXXV",
  "100111XXXXXGXHXHHXLXXXXV",
  "101000XXXXXGXLXLHXHXXXXV",
  "101001XXXXXGXLXHLXHXXXXV",
  "101010XXXXXGXLXHHXHXXXXV",
  "101011XXXXXGXHXLLXLXXXXV",
  "101100XXXXXGXHXLHXLXXXXV",
  "101101XXXXXGXHXHLXLXXXXV",
  "101110XXXXXGXHXHHXLXXXXV",
  "101111XXXXXGXHXLLXHXXXXV",
  "110000XXXXXGXLXHLXHXXXXV",
  "110001XXXXXGXLXHHXHXXXXV",
  "110010XXXXXGXHXLLXLXXXXV",
  "110011XXXXXGXHXLHXLXXXXV",
  "110100XXXXXGXHXHLXLXXXXV",
  "110101XXXXXGXHXHHXLXXXXV",
  "110110XXXXXGXHXLLXHXXXXV",
  "110111XXXXXGXHXLHXHXXXXV",
  "111000XXXXXGXLXHHXHXXXXV",
  "111001XXXXXGXHXLLXLXXXXV",
  "111010XXXXXGXHXLHXLXXXXV",
  "111011XXXXXGXHXHLXLXXXXV",
  "111100XXXXXGXHXHHXLXXXXV",
  "111101XXXXXGXHXLLXHXXXXV",
  "111110XXXXXGXHXLHXHXXXXV",
  "111111XXXXXGXHXHLXHXXXXV",
]
