#!/usr/bin/env python3
"""
Generate a Logisim-format truth table (.txt) by evaluating a Python class over all
input combinations. The class defines INPUTS (name -> bits), OUTPUTS (name -> bits),
and compute(**kwargs) -> dict of output values.

Supports arbitrary-precision int for >32 bits of input, streaming output (no full
table in memory), and parallel workers (-j N) that each write a body-only part file;
the main process merges parts in order via streaming.

Usage:
  python3 scripts/gen_truth_table.py -i spec.py -o table.txt
  python3 scripts/gen_truth_table.py -i spec.py -o table.txt -j 4
  cat spec.py | python3 scripts/gen_truth_table.py -i - -o table.txt
"""

import argparse
import os
import sys
import multiprocessing


LOGISIM_HEADER_COMMENT = """# Truth table
# Generated by gen_truth_table.py

# Hints and Notes on Formatting:
# * You can edit this file then import it back into Logisim!
# * Anything after a '#' is a comment and will be ignored.
# * Blank lines and separator lines (e.g., ~~~~~~) are ignored.
# * Keep column names simple (no spaces, punctuation, etc.)
# * 'Name[N..0]' indicates an N+1 bit variable, whereas
#   'Name' by itself indicates a 1-bit variable.
# * You can use 'x' or '-' to indicate "don't care" for both
#   input and output bits.
# * You can use binary (e.g., '10100011xxxx') notation or
#   or hex (e.g., 'C3x'). Logisim will figure out which is which.

"""


def normalize_spec(spec):
    """Convert INPUTS/OUTPUTS from list of (name, bits) or dict to list of (name, bits)."""
    if spec is None:
        return None
    if hasattr(spec, "items"):
        return list(spec.items())
    return list(spec)


def spec_to_header_token(name, bits):
    """Logisim header token: 'name' for 1 bit, 'name[bits-1..0]' for multi-bit."""
    if bits <= 1:
        return name
    return f"{name}[{bits - 1}..0]"


def to_bin(val, bits):
    """Format integer value as binary string of exactly `bits` bits (masked)."""
    if bits <= 0:
        return ""
    mask = (1 << bits) - 1
    v = int(val) & mask
    return format(v, "0" + str(bits) + "b")


def compute_sizes_strides(inputs_list):
    """inputs_list = [(name, bits), ...]. Returns (sizes, strides) with ints."""
    sizes = [1 << int(b) for _, b in inputs_list]
    strides = [1]
    for s in reversed(sizes[1:]):
        strides.append(strides[-1] * s)
    strides = list(reversed(strides))
    return sizes, strides


def decode_index(i, inputs_list, sizes, strides):
    """Decode row index i into a dict of input name -> value (int)."""
    return {
        inputs_list[j][0]: (i // strides[j]) % sizes[j]
        for j in range(len(inputs_list))
    }


def format_row(inputs_list, outputs_list, input_vals, output_vals):
    """Format one data line: input bits | output bits (space-separated per column)."""
    in_parts = [
        to_bin(input_vals[inputs_list[j][0]], inputs_list[j][1])
        for j in range(len(inputs_list))
    ]
    out_parts = [
        to_bin(output_vals.get(outputs_list[j][0], 0), outputs_list[j][1])
        for j in range(len(outputs_list))
    ]
    return " ".join(in_parts) + " | " + " ".join(out_parts)


def load_class_from_code(code_str, class_name):
    """Execute code_str and return the class named class_name."""
    ns = {}
    exec(code_str, ns)
    cls = ns.get(class_name)
    if cls is None:
        raise ValueError(f"Class {class_name!r} not found in provided code")
    return cls


def load_class_from_file(path, class_name):
    """Load and execute Python file, return the class named class_name."""
    with open(path, "r", encoding="utf-8") as f:
        code_str = f.read()
    return load_class_from_code(code_str, class_name)


def find_single_class(ns):
    """Return the name of the first class defined in namespace (excluding builtins)."""
    for name, obj in ns.items():
        if (
            isinstance(obj, type)
            and name != "type"
            and not name.startswith("_")
        ):
            return name
    return None


def get_class_and_name(code_str=None, file_path=None, class_name=None):
    """Load code from code_str or file_path, return (class, class_name)."""
    if code_str is not None:
        ns = {}
        exec(code_str, ns)
    else:
        with open(file_path, "r", encoding="utf-8") as f:
            code_str = f.read()
        ns = {}
        exec(code_str, ns)
    if class_name:
        cls = ns.get(class_name)
        if cls is None:
            raise ValueError(f"Class {class_name!r} not found")
    else:
        class_name = find_single_class(ns)
        if class_name is None:
            raise ValueError("No class found in provided code; use -c ClassName")
        cls = ns[class_name]
    return cls, class_name


def run_worker(args):
    """Worker entry: generate body rows for indices [start, end) and write to part_path.
    args: (code_str, file_path, class_name, inputs_list, outputs_list, start, end, part_path)
    Either code_str or file_path is set; the other is None.
    """
    (
        code_str,
        file_path,
        class_name,
        inputs_list,
        outputs_list,
        start,
        end,
        part_path,
    ) = args
    if code_str is not None:
        cls = load_class_from_code(code_str, class_name)
    else:
        cls = load_class_from_file(file_path, class_name)
    instance = cls()
    sizes, strides = compute_sizes_strides(inputs_list)
    i = start
    with open(part_path, "w", encoding="utf-8") as f:
        while i < end:
            kwargs = decode_index(i, inputs_list, sizes, strides)
            try:
                out = instance.compute(**kwargs)
            except Exception as e:
                raise RuntimeError(f"compute() failed at row index i={i}: {e}") from e
            if not isinstance(out, dict):
                raise TypeError(f"compute() must return a dict, got {type(out)} at i={i}")
            mask_out = {}
            for j, (name, bits) in enumerate(outputs_list):
                val = out.get(name, 0)
                mask = (1 << bits) - 1
                mask_out[name] = int(val) & mask
            line = format_row(inputs_list, outputs_list, kwargs, mask_out)
            f.write(line + "\n")
            i += 1
    return part_path


def run_single_process(cls, inputs_list, outputs_list, num_rows, out_path):
    """Generate full table in one process: header + body, streaming."""
    sizes, strides = compute_sizes_strides(inputs_list)
    instance = cls()
    header_line = " ".join(
        spec_to_header_token(name, bits) for name, bits in inputs_list
    ) + " | " + " ".join(
        spec_to_header_token(name, bits) for name, bits in outputs_list
    )
    sep_len = max(len(header_line), 40)
    separator = "~" * sep_len + "\n"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(LOGISIM_HEADER_COMMENT)
        f.write(header_line + "\n")
        f.write(separator)
        i = 0
        while i < num_rows:
            kwargs = decode_index(i, inputs_list, sizes, strides)
            try:
                out = instance.compute(**kwargs)
            except Exception as e:
                raise RuntimeError(f"compute() failed at row index i={i}: {e}") from e
            if not isinstance(out, dict):
                raise TypeError(f"compute() must return a dict, got {type(out)} at i={i}")
            mask_out = {}
            for name, bits in outputs_list:
                val = out.get(name, 0)
                mask = (1 << bits) - 1
                mask_out[name] = int(val) & mask
            line = format_row(inputs_list, outputs_list, kwargs, mask_out)
            f.write(line + "\n")
            i += 1


def merge_parts_streaming(part_paths, out_path, header_line):
    """Write out_path: header comment + header line + separator + contents of each
    part file in order, reading each part in streaming fashion (no full load).
    """
    sep_len = max(len(header_line), 40)
    separator = "~" * sep_len + "\n"
    with open(out_path, "w", encoding="utf-8") as out_f:
        out_f.write(LOGISIM_HEADER_COMMENT)
        out_f.write(header_line + "\n")
        out_f.write(separator)
        for p in part_paths:
            try:
                with open(p, "r", encoding="utf-8") as inp_f:
                    for line in inp_f:
                        out_f.write(line if line.endswith("\n") else line + "\n")
            finally:
                try:
                    os.remove(p)
                except OSError:
                    pass


def main():
    parser = argparse.ArgumentParser(
        description="Generate Logisim truth table from a Python class (INPUTS, OUTPUTS, compute)."
    )
    parser.add_argument(
        "-i",
        "--input",
        metavar="FILE",
        default=None,
        help="Python file with the class, or '-' to read from STDIN",
    )
    parser.add_argument(
        "-o",
        "--output",
        metavar="FILE",
        default="truth_table.txt",
        help="Output .txt file (default: truth_table.txt)",
    )
    parser.add_argument(
        "-c",
        "--class",
        dest="class_name",
        metavar="NAME",
        default=None,
        help="Class name (default: only class in module)",
    )
    parser.add_argument(
        "-j",
        "--jobs",
        type=int,
        default=1,
        metavar="N",
        help="Number of parallel workers (default: 1)",
    )
    args = parser.parse_args()

    if args.input is None:
        parser.error("Input required: use -i FILE or -i - for STDIN")

    if args.input == "-":
        code_str = sys.stdin.read()
        file_path = None
    else:
        code_str = None
        file_path = args.input
        if not os.path.isfile(file_path):
            sys.exit(f"Error: file not found: {file_path}")

    try:
        if code_str is not None:
            ns = {}
            exec(code_str, ns)
            if args.class_name:
                cls = ns.get(args.class_name)
            else:
                args.class_name = find_single_class(ns)
                cls = ns.get(args.class_name) if args.class_name else None
            if cls is None:
                if args.class_name:
                    sys.exit(f"Error: class {args.class_name!r} not found")
                sys.exit("Error: no class found in code; define one class or use -c Name")
        else:
            cls, args.class_name = get_class_and_name(
                file_path=file_path, class_name=args.class_name
            )
    except Exception as e:
        sys.exit(f"Error loading class: {e}")

    inputs_raw = getattr(cls, "INPUTS", None)
    outputs_raw = getattr(cls, "OUTPUTS", None)
    compute_method = getattr(cls, "compute", None)
    if not inputs_raw:
        sys.exit("Error: class must define INPUTS (list or dict of (name, bits))")
    if not outputs_raw:
        sys.exit("Error: class must define OUTPUTS (list or dict of (name, bits))")
    if not callable(compute_method):
        sys.exit("Error: class must define compute(self, **kwargs) -> dict")

    inputs_list = normalize_spec(inputs_raw)
    outputs_list = normalize_spec(outputs_raw)
    if not inputs_list or not outputs_list:
        sys.exit("Error: INPUTS and OUTPUTS must be non-empty")

    num_rows = 1
    for _, b in inputs_list:
        num_rows *= 1 << int(b)

    out_path = args.output
    num_jobs = max(1, int(args.jobs))

    if num_jobs == 1:
        run_single_process(cls, inputs_list, outputs_list, num_rows, out_path)
        print(f"Wrote {num_rows} rows to {out_path}", file=sys.stderr)
        return

    chunk_size = num_rows // num_jobs
    remainder = num_rows % num_jobs
    starts = []
    ends = []
    for k in range(num_jobs):
        start_k = k * chunk_size + (k if k < remainder else remainder)
        end_k = start_k + chunk_size + (1 if k < remainder else 0)
        starts.append(start_k)
        ends.append(end_k)
    part_paths = [f"{out_path}.part_{k}" for k in range(num_jobs)]

    worker_args = [
        (
            code_str,
            file_path,
            args.class_name,
            inputs_list,
            outputs_list,
            starts[k],
            ends[k],
            part_paths[k],
        )
        for k in range(num_jobs)
    ]

    with multiprocessing.Pool(processes=num_jobs) as pool:
        pool.map(run_worker, worker_args)

    header_line = (
        " ".join(spec_to_header_token(n, b) for n, b in inputs_list)
        + " | "
        + " ".join(spec_to_header_token(n, b) for n, b in outputs_list)
    )
    merge_parts_streaming(part_paths, out_path, header_line)
    print(f"Wrote {num_rows} rows to {out_path} ({num_jobs} workers)", file=sys.stderr)


if __name__ == "__main__":
    main()
